import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";

import React from "react";
import { Footer } from "@/components/Footer";
import { FullScreenNav, MobileNav } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} min-h-screen bg-stone-200 text-stone-800`}
      >
        <main>
          <FullScreenNav />
          <MobileNav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
